version: "3"

services:
  ieuler-server:
    image: liamcryan/ieuler-server
    environment:
      - DB_HOST=mysql
    env_file:
      - .mysql-env
    command: ["wait-for-it", "mysql:3306", "--", "gunicorn", "-b", "0.0.0.0:2718", "app:create_app()"]

  mysql:
    image: mysql
    env_file:
      - .mysql-env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  ttyd:
    build: ./ttyd/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://socat:2375
    ports:
      - 8080:7681
    command: ["/usr/bin/ttyd", "docker", "run", "-it", "--rm", "--env", "IEULER_SERVER_HOST=ieuler-server", "--env", "IEULER_SERVER_PORT=2718", "--network", "interactive-project-euler_default", "liamcryan/ieuler"]

  socat:
    image: bpack/socat
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "2375"