version: "3"

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-app
    expose:
      - 5000
    command: ["gunicorn", "-b", "0.0.0.0:5000", "app:create_app()"]
    volumes:
      - ./app:/usr/local/ipe/app

  ttyd:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-ttyd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ttyd.sh:/usr/local/ttyd/ttyd.sh
    environment:
      - DOCKER_HOST=tcp://socat:2375
    expose:
      - 7681
    command: ["/usr/bin/ttyd", "-a", "./ttyd.sh"]

  ieuler-server:
    restart: always
    image: liamcryan/ieuler-server
    environment:
      - DB_HOST=mysql
    env_file:
      - .mysql-env
    command: ["wait-for-it", "mysql:3306", "--", "gunicorn", "-b", "0.0.0.0:2718", "app:create_app()"]

  mysql:
    restart: always
    image: mysql
    env_file:
      - .mysql-env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  socat:
    restart: always
    image: bpack/socat
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 2375

  nginx:
    restart: always
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - /path/in/host/fullchain.pem:/etc/nginx/fullchain.pem:ro
      # - /path/in/host/privkey.pem:/etc/nginx/privkey.pem:ro
    ports:
      - 80:80
      - 443:443
