version: "3"

services:

  ttyd:
    build: ./ttyd/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://socat:2375
    ports:
      - 8080:7681
    entrypoint: ["/usr/bin/ttyd", "docker", "run", "-it", "--rm", "liamcryan/ieuler"]

  socat:
    image: bpack/socat
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "2375"