FROM ubuntu

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install python3-pip -y \
    && apt-get install git -y \
    && pip3 install --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org git+https://github.com/liamcryan/ieuler flask gunicorn

RUN useradd -ms /bin/bash -d /usr/local/ipe ipe \
    && chown -R ipe: /usr/local/ipe

WORKDIR /usr/local/ipe

USER ipe
